### ISSUE TITLE
Confidence value scale

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/mmath#10]
I'm torn weather the confidence value should be 
a) 100.000 - 0.000 
b) 1.000000 - 0.000000

I first implemented it as optioon `a`, however the more I think about it the `b` solution is better

**Comment by Licenser** [comment]
@szarsti what's your take on this?

**Comment by szarsti** [comment]
I like it to be 0.0 - 1.0, so it behaves like alpha channel. It will be also more useful for mathematical operations.

**Comment by Licenser** [comment]
it's 0.0-1.0 now
