### ISSUE TITLE
undefined symbol be64toh

### ISSUE THREAD

**Issue by patrobinson** [dalmatinerdb/mmath#29]
Running on Ubuntu Xenial, Erlang/OTP 18. mmath compiles fine but when I call `mmath:from_list` I get an error:

```
=WARNING REPORT==== 31-Oct-2016::04:49:27 ===
The on_load function for module mmath_bin returned {error,
                                                    {load_failed,
                                                     "Failed to load NIF library: '/home/ubuntu/ddb_client/_build/default/lib/mmath/priv/bin_nif.so: undefined symbol: be64toh'"}}
** exception error: undefined function mmath_bin:from_list/1
```

I tried various things, including adding `#define _BSD_SOURCE` to `mmath.h` and removing the `-std=c99` compile flag but no luck

**Comment by Licenser** [comment]
@davecromberge I know you're compiling mmath on linux, any chance you've seen this before?

**Comment by davecromberge** [comment]
@patrobinson I managed to reproduce this on Xenial, and am still investigating a fix.  Could you use an earlier version of Ubuntu such as Trusty in the mean time?

**Comment by carlo-activia** [comment]
When using ddb_client library, I got same error:

starting** exception error: undefined function mmath_bin:from_list/1
     in function  dalmatinerdb:start/0 (dalmatinerdb.erl, line 14)
2> 
=ERROR REPORT==== 2-Nov-2016::21:03:50 ===
The on_load function for module mmath_bin returned {error,
                                                    {load_failed,
                                                     "Failed to load NIF library: 'priv/bin_nif.so: undefined symbol: be64toh'"}}


I ran it on Ubuntu 16.04 using Erlang/OTP 18 and also
on Ubuntu 14.04.5 docker image using Erlang R16B03

**Comment by Licenser** [comment]
From some googling it looked like the `be64toh` function is part of some kernel libary, could it be that daves Trusty and 16/14 use different kernel versions? 2.x vs 3.x or something?

**Comment by carlo-activia** [comment]
My Ubuntu 14.04.5 and Ubuntu 16.04 both use kernel 4.x
Also tried in Centos 7 (kernel 4.x), same error message

**Comment by carlo-activia** [comment]
BTW, my Centos 7 and Ubuntu 14.04.5 are docker containers, so it might get the kernel version of the docker host which is 4.x

**Comment by Licenser** [comment]
There is a 4.x kernel now? Wow I really have not kept up to date with Linux land o.O

**Comment by davecromberge** [comment]
@Licenser you are right. My Trusty kernel version is version 3.13, and Xenial (where I get the problem) is running kernel version 4.4.

**Comment by Licenser** [comment]
@carlo-activia, @patrobinson can one of you look on your systems what the manpage for ENDIAN(3) tells you? That's where the be64toh function should be.

**Comment by carlo-activia** [comment]
I ran it on Linux: ubuntu Precise (12.04.5) with kernel 3.13.0-32-generic and still get the error :(
Regarding the "man endian" command, in Ubuntu16  it says 

ENDIAN(3)

NAME
       htobe16, htole16, be16toh, le16toh, htobe32, htole32, be32toh, le32toh, htobe64, htole64, be64toh, le64toh - convert values between host and big-/little-endian byte order

In Ubuntu 12, I got 

No manual entry for endian

**Comment by patrobinson** [comment]
I think this is relevant:

```
       _BSD_SOURCE (deprecated since glibc 2.20)
              Defining this macro with any value causes header files to expose BSD-derived definitions.

              In glibc versions up to and including 2.18, defining this macro also causes BSD definitions to be preferred in some situations where standards conflict, unless
              one  or  more  of _SVID_SOURCE, _POSIX_SOURCE, _POSIX_C_SOURCE, _XOPEN_SOURCE, _XOPEN_SOURCE_EXTENDED, or _GNU_SOURCE is defined, in which case BSD definitions
              are disfavored.  Since glibc 2.19, _BSD_SOURCE no longer causes BSD definitions to be preferred in case of conflicts.

              Since glibc 2.20, this macro is deprecated.  It  now  has  the  same  effect  as  defining  _DEFAULT_SOURCE,  but  generates  a  compile-time  warning  (unless
              _DEFAULT_SOURCE is also defined).  Use _DEFAULT_SOURCE instead.  To allow code that requires _BSD_SOURCE in glibc 2.19 and earlier and _DEFAULT_SOURCE in glibc
              2.20 and later to compile without warnings, define both _BSD_SOURCE and _DEFAULT_SOURCE.
```

I tested on debian jessie (glibc 2.19) and it worked. Ubuntu Xenial runs glibc 2.23, i'm trying to setup an environment to test using _DEFAULT_SOURCE and/or __USE_MISC as described here https://lwn.net/Articles/590381/
