### ISSUE TITLE
decimal floating point numbers break mmath_aggr:scale/2

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/mmath#3]
Simple test:

```erlang
mmath_aggr:scale(mmath_bin:from_list([1.0,2,3]), 2.0).
```

**Comment by Licenser** [comment]
cc @szarsti

**Comment by szarsti** [comment]
I have a fix for that on my branch. Right now I am pulling you changes from branch 0.2 and will prepare pull-request with all of that. I ended up having quite a few collisions with confidence branches, so it may take me a bit to have it tested.

**Comment by Licenser** [comment]
this is depricated
